getlist([]).
getlist([X,Y]):-resolve(X,Y,R),write(R),!.
getlist([X,Y|Z]):-resolve(X,Y,R),append([R],Z,R1),getlist(R1).
resolve([],Y,Y).
resolve([X|X1],Y,R):-checkwith(X,Y,R1,M),M==[],resolve(X1,R1,R),!.
resolve([X|X1],Y,R):-checkwith(X,Y,R2,M),M\=[],addelement(X,R2,R1),resolve(X1,R1,R).
checkwith(X,[],[],X).
checkwith(X,[Y|Y1],R,X1):-X==Y,checkwith(X,Y1,R,X1),!.
checkwith(X,[Y|Y1],Y1,[]):-X==not(Y).
checkwith(X,[Y|Y1],Y1,[]):-Y==not(X).
checkwith(X,[Y|Y1],R,X1):-X\=Y,checkwith(X,Y1,R1,X1),addelement(Y,R1,R),!.
notin(X,[]).
notin(X,[Y|Z]):-X\=Y,notin(X,Z).
addelement(X,Y,[X|Y]).
